"""Intrinsic canvas geometry for generative vector artwork."""

from .design import (
    AlgorithmCapabilities,
    DesignPass,
    DesignResult,
    DesignState,
    DomainAlgorithm,
    LogicalLayer,
    VectorPath,
    execute_design_pass,
    execute_design_passes,
    validate_pass_graph,
)
from .frames import (
    AffineTransform,
    CompositionTransform,
    resolve_composition_transforms,
)
from .geometry import (
    CanvasError,
    CanvasGeometry,
    build_canvas,
    is_convex_polygon,
    polygon_centroid,
    polygon_edges,
    polygon_signed_area,
    polygon_winding,
    validate_simple_polygon,
)
from .models import CanvasSpec, DomainProvenance, Edge, Point, PolygonDomain
from .semantics import (
    DomainRef,
    DomainRelation,
    FeatureRef,
    FeatureType,
    PolygonGroup,
    PolygonSurface,
    RelationEndpoint,
    RelationType,
    validate_semantics,
)

__all__ = [
    "AlgorithmCapabilities",
    "AffineTransform",
    "CanvasError",
    "CanvasGeometry",
    "CanvasSpec",
    "CompositionTransform",
    "DesignPass",
    "DesignResult",
    "DesignState",
    "DomainProvenance",
    "DomainRef",
    "DomainRelation",
    "DomainAlgorithm",
    "Edge",
    "FeatureRef",
    "FeatureType",
    "LogicalLayer",
    "Point",
    "PolygonDomain",
    "PolygonGroup",
    "PolygonSurface",
    "RelationEndpoint",
    "RelationType",
    "VectorPath",
    "build_canvas",
    "execute_design_pass",
    "execute_design_passes",
    "is_convex_polygon",
    "polygon_centroid",
    "polygon_edges",
    "polygon_signed_area",
    "polygon_winding",
    "resolve_composition_transforms",
    "validate_simple_polygon",
    "validate_semantics",
    "validate_pass_graph",
]
